module TestExamplesP4estMesh2D

using Test
using Trixi

include("test_trixi.jl")

EXAMPLES_DIR = joinpath(examples_dir(), "p4est_2d_dgsem")

# Start with a clean environment: remove Trixi.jl output directory if it exists
outdir = "out"
isdir(outdir) && rm(outdir, recursive = true)

@testset "P4estMesh" begin
    @trixi_testset "elixir_euler_NACA6412airfoil_supersonic.jl" begin
        # The mesh is generated by Gmsh at run time, so it may differ slightly between
        # Gmsh versions. Rather than exact values, we check the L2 distance of the solution
        # from the initial condition, a global quantity that changes by more than the
        # tolerance of 1.5% between these meshes, but by less between different meshes
        # of the same resolution.
        @test_trixi_include(joinpath(EXAMPLES_DIR,
                                     "elixir_euler_NACA6412airfoil_supersonic.jl"),
                            mesh_size=0.2, tspan=(0.0, 0.3),
                            l2=[
                                0.29466862443581027,
                                0.52498108172213565,
                                0.27945257968907522,
                                1.1983133578781067
                            ],
                            rtol=0.015)
        @test_trixi_include(joinpath(EXAMPLES_DIR,
                                     "elixir_euler_NACA6412airfoil_supersonic.jl"),
                            mesh_size=0.15, tspan=(0.0, 0.3),
                            l2=[
                                0.30169184902281404,
                                0.53436291285740833,
                                0.2864397524240162,
                                1.2243680425405681
                            ],
                            rtol=0.015)
        @test_trixi_include(joinpath(EXAMPLES_DIR,
                                     "elixir_euler_NACA6412airfoil_supersonic.jl"),
                            mesh_size=0.1, tspan=(0.0, 0.3),
                            l2=[
                                0.3087425246676801,
                                0.54481127319769651,
                                0.29458365585142876,
                                1.2520902006174484
                            ],
                            rtol=0.015)
        # Ensure that we do not have excessive memory allocations
        # (e.g., from type instabilities)
        @test_allocations(Trixi.rhs_hyperbolic!, semi, sol, 1000)
    end

    @trixi_testset "elixir_euler_NACA0012airfoil_mach08.jl" begin
        @test_trixi_include(joinpath(EXAMPLES_DIR,
                                     "elixir_euler_NACA0012airfoil_mach08.jl"),
                            l2=[
                                1.4825298121291054e-5,
                                1.1299955298727266e-5,
                                1.5024395928115724e-5,
                                3.9872656618032726e-5
                            ],
                            linf=[
                                0.6355977259450771,
                                1.1180698298562255,
                                0.6836203300405327,
                                1.4202190591669863
                            ],
                            tspan=(0.0, 0.1))
        # Ensure that we do not have excessive memory allocations
        # (e.g., from type instabilities)
        @test_allocations(Trixi.rhs_hyperbolic!, semi, sol, 1000)
    end

    @trixi_testset "elixir_navierstokes_NACA0012airfoil_mach08.jl" begin
        @test_trixi_include(joinpath(EXAMPLES_DIR,
                                     "elixir_navierstokes_NACA0012airfoil_mach08.jl"),
                            l2=[
                                0.0013329924272079746,
                                0.004524576282253344,
                                0.0024055822778919415,
                                0.01462132950009296
                            ],
                            linf=[
                                0.694673794075408,
                                1.7937600476958173,
                                1.0952815158719686,
                                6.725234662117499
                            ],
                            tspan=(0.0, 0.02))
        # Ensure that we do not have excessive memory allocations
        # (e.g., from type instabilities)
        @test_allocations(Trixi.rhs_hyperbolic!, semi, sol, 1000)
        @test_allocations(Trixi.rhs_parabolic!, semi, sol, 1000)
    end
end

end # module
